services:
  eventos:
    build:
      context: ./eventos  # Contexto para el microservicio de Java
    container_name: eventos-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:5432/db_eventos
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: utec
    networks:
      - api

  usuarios:
    build:
      context: ./usuarios  # Contexto para el microservicio de Python
    container_name: usuarios-api
    ports:
      - "8000:8000"
    volumes:
      - ./usuarios:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      MYSQL_HOST: ${DB_HOST}  
      MYSQL_USER: root
      MYSQL_PASSWORD: utec
    networks:
      - api

networks:
  api:
    driver: bridge



# Probar usuarios: http://localhost:8000/docs
# Probar eventos: http://localhost:8080/swagger-ui/index.html#/
