services:
  mysql-usuarios:
    image: mysql:8
    container_name: mysql_c
    environment:
      MYSQL_ROOT_PASSWORD: utec
      MYSQL_DATABASE: db_usuarios
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - network

  postgres-eventos:
    image: postgres:15
    container_name: postgres_c
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: utec
      POSTGRES_DB: db_eventos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - network

  mongo-ventas:
    image: mongo
    container_name: mongo_c
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - network

  adminer:
    image: adminer
    container_name: adminer_c
    ports:
      - "8080:8080"
    networks:
      - network

volumes:
  mysql_data:
  postgres_data:
  mongo_data:

networks:
  network:
